### PR TITLE
Use ActivityViewModelContext for activity scope

### PR DESCRIPTION
**Pull request by apramana**
Fixes: #674 

parentFragment should not get set if the scope is an activity.

### CODE REVIEW

**Comment by vulpeszerda** [comment]
@apramana 
I think just removing `findFragmentFromView` discards some functionality.

How about this?

```kotlin
val parentFragment = scope as? Fragment ?: if (scope !is Activity) findFragmentFromView(view) else null

if (parentFragment != null) {
    val args = argsFactory?.invoke() ?: parentFragment.arguments?.get(Mavericks.KEY_ARG)
    FragmentViewModelContext(activity, args, parentFragment)
} else {
    val args = argsFactory?.invoke() ?: activity.intent.extras?.get(Mavericks.KEY_ARG)
    ActivityViewModelContext(activity, args, viewModelStoreOwner, savedStateRegistry)
}
```

**Comment by apramana** [comment]
> @apramana I think just removing `findFragmentFromView` discards some functionality.
> 
> How about this?
> 
> ```kotlin
> val parentFragment = scope as? Fragment ?: if (scope !is Activity) findFragmentFromView(view) else null
> 
> if (parentFragment != null) {
>     val args = argsFactory?.invoke() ?: parentFragment.arguments?.get(Mavericks.KEY_ARG)
>     FragmentViewModelContext(activity, args, parentFragment)
> } else {
>     val args = argsFactory?.invoke() ?: activity.intent.extras?.get(Mavericks.KEY_ARG)
>     ActivityViewModelContext(activity, args, viewModelStoreOwner, savedStateRegistry)
> }
> ```

@vulpeszerda when would scope be neither a Fragment nor an Activity? It seems like `findFragmentFromView()` would never get called...

**Comment by apramana** [comment]
> @apramana I think just removing `findFragmentFromView` discards some functionality.
> 
> How about this?
> 
> ```kotlin
> val parentFragment = scope as? Fragment ?: if (scope !is Activity) findFragmentFromView(view) else null
> 
> if (parentFragment != null) {
>     val args = argsFactory?.invoke() ?: parentFragment.arguments?.get(Mavericks.KEY_ARG)
>     FragmentViewModelContext(activity, args, parentFragment)
> } else {
>     val args = argsFactory?.invoke() ?: activity.intent.extras?.get(Mavericks.KEY_ARG)
>     ActivityViewModelContext(activity, args, viewModelStoreOwner, savedStateRegistry)
> }
> ```

Yeah I suppose scope could be a non-fragment/activity lifecycle owner... updated to use a when expression.

**Review by elihart — COMMENTED** [review]
Thanks for the fix @apramana - can you add a unit test?

**Comment by elihart** [comment]
Thanks!

**Comment by rossbacher** [comment]
@apramana This is now part of release [v3.0.6](https://github.com/airbnb/mavericks/releases/tag/v3.0.6) that I just made.

**Comment by apramana** [comment]
> @apramana This is now part of release [v3.0.6](https://github.com/airbnb/mavericks/releases/tag/v3.0.6) that I just made.

Thanks @rossbacher !

**Pull request merged**
